import fs from 'fs';
import path from 'path';
import source from 'src/config';
import jsToSass from './utils/jsToSass';
import deepMerge from './utils/deepMerge';
import {
  errorLog,
  successLog,
} from './utils/log';

const generateContent = ({
  theme,
}) => {
  const cssConfig = deepMerge(source, theme);
  const variables = jsToSass(cssConfig);

  const processRoot = process.cwd();
  let thisFilename;
  const root = path.resolve(__dirname, '../../');
  const relativeRoot = path.relative(root, processRoot);
  if (relativeRoot.startsWith('../')) {
    thisFilename = '@aztec/guacamole-ui';
  } else {
    thisFilename = path.relative(processRoot, __filename);
  }

  return `// auto-generated by ${thisFilename}
${variables}
  `;
};

const getFileDest = ({
  output: {
    path: outputPath = path.resolve(__dirname, '../../src/styles'),
    variablesFilename = 'variables.scss',
  } = {},
}) => path.join(outputPath, variablesFilename);

export const generateSassVariablesSync = (confifg = {}) => {
  const content = generateContent(confifg);
  const fileDest = getFileDest(confifg);

  try {
    fs.writeFileSync(fileDest, content);
    successLog('Sass variables file created', `path: ${fileDest}`);
  } catch (error) {
    errorLog(error);
    process.exit(1);
  }
};

export default async function generateSassVariables(confifg = {}) {
  const content = generateContent(confifg);
  const fileDest = getFileDest(confifg);

  await fs.writeFile(fileDest, content, (error) => {
    if (error) {
      errorLog(error);
      process.exit(1);
    } else {
      successLog(
        'Sass variables file created',
        `  path: ${fileDest}`,
      );
    }
  });
}
