import fs from 'fs';
import path from 'path';
import source from 'src/config';
import jsToSass from '../utils/jsToSass';
import {
  errorLog,
  successLog,
} from '../utils/log';

const FILE_DEST = './src/styles/variables.scss';

export default async function generateSassVariables(dest = FILE_DEST) {
  const root = path.resolve(__dirname, '../../');
  const thisFilename = path.relative(root, __filename);
  const variables = jsToSass(source);
  const content = `// auto-generated by ${thisFilename}
${variables}
  `;

  await fs.writeFile(path.resolve(root, dest), content, (err) => {
    if (err) {
      errorLog(err);
      process.exit(1);
    }

    successLog(`File created: ${dest}`);
  });
}
